rust_compiler_version:
  - 1.64.0
macos_min_version:
  - 11.13  # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:
  - 11.3  # [osx and arm64]
MACOSX_SDK_VERSION:
  - "11.3"                 # [osx and arm64]
CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  # [osx and arm64]