# Rust version requirement in upstream README.md
rust_compiler_version:
  - 1.76.0
# orjson has wheels only for MacOS SDK 11.0, see https://pypi.org/project/orjson/3.8.8/#files
MACOSX_DEPLOYMENT_TARGET:
  - 11.0  # [osx and arm64]
MACOSX_SDK_VERSION:
  - "11.0"                 # [osx and arm64]
# https://github.com/rust-lang/rust/pull/104385
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.12.sdk        # [osx and x86_64]