{% set name = "orjson" %}
{% set version = "3.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b1a67243945819ce55d24a30b59d6a168e86220452d2c96f4d1f093e71c0c49

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - maturin >=1,<2
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test
  imports:
    - orjson
  requires:
    - pip
    - mypy
    - pytest >=9.0
  commands:
    - pip check
    - mypy -m orjson
    - pytest -v test

about:
  home: https://github.com/ijl/orjson
  license: MPL-2.0 AND (Apache-2.0 OR MIT)
  license_family: OTHER
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    # Collected from cargo during the build
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  description: |
    orjson is a fast, correct JSON library for Python. It benchmarks as the fastest Python
    library for JSON and is more correct than the standard json library or other third-party
    libraries. It serializes dataclass, datetime, numpy, and UUID instances natively.
  doc_url: https://github.com/ijl/orjson/blob/{{ version }}/README.md
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
    - bkreider
