{% set name = "orjson" %}
{% set version = "3.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39485f4ab4c9b30a3943cfe99e1a213c4776fb69e8abd68f66b83d5a0b0fdc6d

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    # https://github.com/ijl/orjson/blob/master/CHANGELOG.md#3112---2025-08-12 says 
    # the minimum rust build version is 1.85
    - {{ compiler('rust') }}
    # Limit clang to the version rust was built against.
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    # https://github.com/ijl/orjson/blob/master/CHANGELOG.md#changed-7
    - maturin >=1,<2
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test
  imports:
    - orjson
  requires:
    - pip
    - mypy
    - pytest
  commands:
    - pip check
    - mypy -m orjson
    - pytest -v test

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0 OR MIT
  license_family: OTHER
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    # Collected from cargo during the build
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  description: |
    orjson is a fast, correct JSON library for Python. It benchmarks as the fastest Python
    library for JSON and is more correct than the standard json library or other third-party
    libraries. It serializes dataclass, datetime, numpy, and UUID instances natively.
  doc_url: https://github.com/ijl/orjson/blob/{{ version }}/README.md
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
    - bkreider
