# There is no gnu version of orjson on Windows
# because the simdutf8 does not get properly linked
{% set name = "orjson" %}
{% set version = "3.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c096d7a523bae6ffb9c4a228ba4691d66113f0f2231579dc945523fbef09c6da

build:
  number: 0
  skip: true  # [py<37 or s390x]

requirements:
  build:
    - rust_win-64  # [win]
    - {{ compiler('rust') }}  # [not win]
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
    - maturin 0.13.7
    - python
    - pip
    - toml
    - wheel
  run:
    - python

test:
  imports:
    - orjson
  requires:
    - pip
    - mypy
  commands:
    - pip check
    - mypy -m orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  description: |
    orjson is a fast, correct JSON library for Python. It benchmarks as the fastest Python
    library for JSON and is more correct than the standard json library or other third-party
    libraries. It serializes dataclass, datetime, numpy, and UUID instances natively.
  doc_url: https://github.com/ijl/orjson/blob/{{ version }}/README.md
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
    - bkreider
