{% set name = "orjson" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a6eeaf247b0e8bfce3695376cfc8658470cd831989380e2a5b1df257e0d481f1
  - url: https://static.rust-lang.org/dist/2020-10-24/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux]
    sha256: 8e8772b9d5c84987d385fc719b5c41b695608dcad45f8796f5718ae29b09422f  # [linux]
    folder: rust-nightly  # [linux]
  - url: https://static.rust-lang.org/dist/2020-10-24/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
    sha256: f47e4484067cb7f5e289f02cb544ebd5eca8aad4744a7305cc0f308de10f3f6c  # [osx]
    folder: rust-nightly  # [osx]
  - url: https://static.rust-lang.org/dist/2020-10-24/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: df7e72420aa7a94a9dd74625653dc0882c85eede71480659e37277da750c92dd  # [win]
    folder: rust-nightly  # [win]

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - posix    # [win]
  host:
    - python
    - pip
    - maturin >=0.8.1,<0.10
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
