{% set name = "orjson" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2dcfc744cad7dceee7fca55ebdca91cc79e14223acc76423f0f4017e7a2676c9
  - url: https://static.rust-lang.org/dist/2020-06-09/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux]
    sha256: 2e59f105bbe2f5a20920734c73c544175ad282e0490ea307bf93b1f9724b85aa  # [linux]
    folder: rust-nightly  # [linux]
  - url: https://static.rust-lang.org/dist/2020-06-09/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
    sha256: 039a822c4652638c0ed27cdf3440b5c5b0fff8eb41902c17e255899b93a13ac2  # [osx]
    folder: rust-nightly  # [osx]
  - url: https://static.rust-lang.org/dist/2020-06-09/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: 7e8f97be7eb32b6f59e40a75e63bc2438a0573092e8312b1be2b52f28f1cc851  # [win]
    folder: rust-nightly  # [win]

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - posix    # [win]
  host:
    - python
    - pip
    - maturin >=0.8.1
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
