{% set name = "orjson" %}
{% set version = "3.6.2" %}
{% set rust_nightly_version = "2021-08-17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f58e8898dbc751c89a6fdd17d32e277b9d5bcf3b0f4e64e028ec962200d9d0ca
    patches:
      - 0001-If-target_arch-not-in-x86_64-aarch64-fallback.patch
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux64]
    sha256: 4e974a672a8cd3e72a8d36fc7711d2a3dd315809bce64c628261b4689cb24edf  # [linux64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
    sha256: a19fcbe870d0fcfc363a8e3383939922b80b9bf6c3ce55202673cc5271a8b4c2  # [ppc64le]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
    sha256: 91878def124c0e25c00afacbaa0013225537acba838eaff9c382a30c181a3a86  # [aarch64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
    sha256: 64cf856fc0780f85db5a134d321af87be3ef37fa20fca06f928570073210cf29  # [osx]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win]
    sha256: 44d4e3daf69eea4420b5dd5cbe76654d63522af100e54d86490367bc75e0f425  # [win]
    folder: rust-nightly
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [target_platform == 'osx-arm64']
    sha256: 9e7f5185466338ac80e0bf2c578b3cef36c10e7939577210dd9f95d0fca413f5  # [target_platform == 'osx-arm64']
    folder: rust-nightly-aarch64-apple-darwin  # [target_platform == 'osx-arm64']

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - posix                               # [win]
  host:
    - python
    - pip
    - maturin >=0.11.2,<0.12
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
