{% set name = "orjson" %}
{% set version = "3.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2e824220245323bb3291bb10ccf2ba936ed0b14e5e4a6260a1d1ed048caf77e

build:
  number: 0
  skip: true  # [py<37 or (osx and arm64) or s390x]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}                 # [not win]
    - posix                               # [win]
    - cargo-bundle-licenses
    - maturin >=0.13,<0.14
  host:
    - python
    - pip
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
    - bkreider
